#! /bin/sh
#### AUTOSTART ####
polybar_launch &
transmission-daemon &
~/.fehbg &


#### MONITORS ####
bspc monitor --reset-desktops 1 2 3 4 5 6 7 8 9 10



#### BSPWM configuration ####
bspc config focus_follows_pointer         true
bspc config border_width                  1
bspc config window_gap                    0
bspc config top_padding                   18
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config split_ratio                   0.60
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


bspc rule -a mpv state=floating
