#! /bin/sh
#### AUTOSTART ####
sxhkd &
xsetroot -cursor_name left_ptr &
transmission-daemon &
polybar_launch &
wmname LG3D &
~/.fehbg &
dunst &
xautolock -locker "i3lock -i ~/Pictures/lock.png" &
compton &
