#! /bin/sh
#### AUTOSTART ####
sxhkd &
xsetroot -cursor_name left_ptr &
polybar_launch &
transmission-daemon &
wmname LG3D &
dunst &
xautolock -locker "i3lock -i ~/Pictures/lock.png" &
compton
~/.fehbg &
