#!/bin/sh
#### AUTOSTART ####
sxhkd &
xsetroot -cursor_name left_ptr &
xrandr --output HDMI-A-0 --set TearFree on &
#sudo modprobe k10temp force=1 &
sudo modprobe zenpowe &
transmission-daemon &
polybar_launch &
wmname LG3D &
~/.fehbg &
dunst &
applets &
xautolock -locker "betterlockscreen -l dim" &
#compton &
syncthing -no-browser &
mpd &
sudo ethtool -s enp5s0 wol g &
sudo radeon-profile & alacritty -e lolminer --coin ETH --pool stratum+tcp://ethash.poolbinance.com:1800 --user zereb --worker w1
