#!/usr/bin/bash
rm /home/oleg/.dir-locals.el
rm -rf /home/oleg/.android
rm -rf /home/oleg/.gdxtexturepackergui
rm -rf /home/oleg/.gnome
rm -rf /home/oleg/.java
rm -rf /home/oleg/.junique
rm -rf /home/oleg/.mitmproxy
rm -rf /home/oleg/.mono
rm -rf /home/oleg/.mozilla
rm -rf /home/oleg/.zoom
rm -rf /home/oleg/.w3m
rm -rf /home/oleg/.cahe
rm -rf /home/oleg/.cargo
rm -rf /home/oleg/.cache/yay
rm -rf /home/oleg/.pki
rm -rf /home/oleg/.parsec
rm -rf /home/oleg/.putty
rm -rf /home/oleg/.visualvm
rm -rf /home/oleg/.vnc
rm -rf /home/oleg/.cache/mozilla
rm -rf /home/oleg/.netrc
rm -rf /home/oleg/.netbeans
rm -rf /home/oleg/.openjfx
rm -rf /home/oleg/.prefs
rm -rf /home/oleg/Documents/Music
rm -rf /home/oleg/Documents/Videos
rm -rf /home/oleg/Documents/Pictures
rm -rf /home/oleg/Documents/Downloads
rm ~/.bash_history
rm ~/.fcuid
rm ~/.grip
rm ~/.grip-oggenc
rm ~/.lesshst
rm ~/.viminfo
rm ~/.wget-hsts

