#!/bin/bash
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

polybar default -r &

second_monitor=$(xrandr --query | grep 'DisplayPort-2')
if [[ $second_monitor = *connected* ]]; then
    polybar second &
fi
