#!/bin/sh
alacritty -t 'main-prod' -e sshpass -p 'UkcyewOawdUrgot4' ssh o.plett@hel.battlesmiths.com  'tail -f /opt/mg/apps/production/platform-main/logs/application.log' &
alacritty -t 'admin-prod'  -e sshpass -p 'UkcyewOawdUrgot4' ssh o.plett@hel.battlesmiths.com  'tail -f /opt/mg/apps/production/platform-admin/logs/application.log' &
alacritty -t 'payment-prod'  -e sshpass -p 'UkcyewOawdUrgot4' ssh o.plett@hel.battlesmiths.com  'tail -f /opt/mg/apps/production/payment-webhooks-service/logs/application.log' &
alacritty -t 'quest-prod'  -e sshpass -p 'UkcyewOawdUrgot4' ssh o.plett@hel.battlesmiths.com  'tail -f opt/mg/apps/production/platform-quest-server/logs/application.log' &

