#!/bin/sh
kitty -T 'main-qa' -e sshpass -p '7Eratbujsegboak5' ssh o.plett@qa.battlesmiths.com  'tail -n 40 -f /opt/mg/apps/platform/qa/platform-main/logs/application.log' &
kitty -T 'admin-qa'  -e sshpass -p '7Eratbujsegboak5' ssh o.plett@qa.battlesmiths.com  'tail -n 40 -f /opt/mg/apps/platform/qa/platform-admin/logs/application.log' &
kitty -T 'payment-qa'  -e sshpass -p '7Eratbujsegboak5' ssh o.plett@qa.battlesmiths.com  'tail -n 40 -f /opt/mg/apps/platform/qa/payment-webhooks-service/logs/application.log' &
kitty -T 'quest-qa'  -e sshpass -p '7Eratbujsegboak5' ssh o.plett@qa.battlesmiths.com  'tail -n 40 -f /opt/mg/apps/platform/qa/platform-quest-server/logs/application.log' &
kitty -T 'quest-distributor-qa'  -e sshpass -p '7Eratbujsegboak5' ssh o.plett@qa.battlesmiths.com 'tail -n 40  -f /opt/mg/apps/platform/qa/quest-distributor-service/logs/application.log' &
kitty -T 'messages-dev'  -e sshpass -p '7Eratbujsegboak5' ssh o.plett@qa.battlesmiths.com 'tail -n 40  -f /opt/mg/apps/platform/qa/platform-messages/logs/application.log' &
