#!/bin/sh
alacritty -t 'main' -e /usr/bin/sshpass -p'cowfEifcoictEgg7' /usr/bin/ssh o.plett@merlin.vintersaga.com  'tail -f /opt/mg/apps/platform/develop/platform-main/logs/application.log' &
alacritty -t 'admin-de'  -e sshpass -p 'cowfEifcoictEgg7' ssh o.plett@merlin.vintersaga.com  'tail -f /opt/mg/apps/platform/develop/platform-admin/logs/application.log' &
alacritty -t 'payment-dev'  -e sshpass -p 'cowfEifcoictEgg7' ssh o.plett@merlin.vintersaga.com  'tail -f /opt/mg/apps/platform/develop/payment-webhooks-service/logs/application.log' &
alacritty -t 'quest'  -e sshpass -p 'cowfEifcoictEgg7' ssh o.plett@merlin.vintersaga.com  'tail -f /opt/mg/apps/platform/develop/platform-quest-server/logs/application.log' &

