#!/usr/bin/env python

import socket
import sys
import argparse


TCP_IP = ['136.169.218.214']
TCP_PORT = 9910
BUFFER_SIZE = 1024
STATUS = "7e00000000017f"
POWER_OFF = "7e070000000d506f7765723d307f"
POWER_ON = "7e070000000d506f7765723d317f"
UPDATE = "7e00000000057f"
REBOOT = "7e00000000717f"


def operate(ips, port, code):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    message = bytes.fromhex(code)
    for ip in TCP_IP:
        print ("Connectig to: " + ip)
        try:
            s.connect((ip, port))
            s.send(message)
            data = s.recv(BUFFER_SIZE)
            s.close()
            print(data)
        except OSError as err:
            print(err)

print ("piked args: ", sys.argv[1:])

for arg in sys.argv[1:]:
    if arg == "--on":
        operate(TCP_IP, TCP_PORT, POWER_ON)
    if arg == "--off":
        operate(TCP_IP, TCP_PORT, POWER_OFF)
    if arg == "--update":
        operate(TCP_IP, TCP_PORT, UPDATE)
    if arg == "--reboot":
        operate(TCP_IP, TCP_PORT, REBOOT)
    if arg == "--status":
        operate(TCP_IP, TCP_PORT, STATUS)
